[project]
name = "handy-dataset"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mediapipe>=0.10.21",
    "pandas>=2.2.3",
    "torch>=2.7.0",
    "torchvision>=0.22.0",
]
